# -*- coding: utf-8 -*-
"""Which (n_disks, n_bearings) family can serve a target band?

The sampler draws the family uniformly from the 18 combinations and lets the
geometry denoiser cope.  For the high tiers that wastes a third of the budget:
measured on the pool, only 12 of 18 families can reach [15200, 16800] for steel
at all, and the share of a family's designs that fall in the band spans 40x
(d1_b4 30.7 per mille against d6_b2 0.73).

This module turns that pool evidence into a family prior

    w_f  proportional to  P_f(band) * prior_f

where P_f(band) is the share of family f's own designs whose cs1 sits in the
band, read off a smoothed histogram of log cs1 per (material, family).  It also
answers the user's other two requirements directly:

    allowed = None            the family is generated by the model
    allowed = [(3, 2)]        the family is pinned by the user
    allowed = [(2,2)..(4,3)]  the family is restricted to a range

so the disk and bearing counts stop being an assumption and become part of what
the design generates, or part of what the user constrains.
"""
import json
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import spec_common as S
import spec_eval as E

FAMILIES = [(a, b) for a in S.ND_CHOICES for b in S.NB_CHOICES]
POLICY_JSON = os.path.join(E.OUT, "family_policy.json")
BINS = 64
ALPHA = 1.0            # Laplace pseudocount per bin
SMOOTH_SIGMA = 1.0     # bins of Gaussian smoothing, so the tails are not gaps


def _grid(ctx):
    cs1 = ctx["Y"][:, 0]
    lo = float(np.log(max(cs1.min(), 1.0))) - 0.05
    hi = float(np.log(cs1.max())) + 0.05
    return np.linspace(lo, hi, BINS + 1)


def _smooth(counts, sigma=SMOOTH_SIGMA):
    if sigma <= 0:
        return counts
    radius = max(1, int(np.ceil(3.0 * sigma)))
    offsets = np.arange(-radius, radius + 1)
    kernel = np.exp(-0.5 * (offsets / sigma) ** 2)
    kernel /= kernel.sum()
    out = np.zeros_like(counts)
    for shift, weight in zip(offsets, kernel):
        out += weight * np.roll(counts, shift, axis=0)
    return out


def fit(ctx=None, bins=BINS, alpha=ALPHA):
    """Per (material, family) histogram of log cs1 over the pool."""
    if ctx is None:
        ctx = E.pool_ctx()
    cs1 = np.log(np.maximum(ctx["Y"][:, 0], 1.0))
    edges = _grid(ctx)
    mat = ctx["material"]
    nd, nb = ctx["nd"], ctx["nb"]
    out = {}
    for material in S.MATERIAL_ORDER:
        for family in FAMILIES:
            sel = (mat == material) & (nd == family[0]) & (nb == family[1])
            counts, _ = np.histogram(cs1[sel], bins=edges)
            counts = _smooth(counts.astype(np.float64) + alpha)
            total = counts.sum()
            out["%s|%d_%d" % (material, family[0], family[1])] = {
                "n": int(sel.sum()), "p": (counts / total).tolist()}
    return {"edges": edges.tolist(), "bins": int(bins), "alpha": float(alpha),
            "sigma": float(SMOOTH_SIGMA), "cells": out, "n_pool": int(len(cs1))}


def save(policy, path=POLICY_JSON):
    S.save_json(path, policy)


def load(path=POLICY_JSON, ctx=None):
    if os.path.exists(path):
        with open(path, encoding="utf-8") as handle:
            return json.load(handle)
    return fit(ctx)


def band_mass(policy, material, family, lower, upper=None):
    """P(cs1 inside [lower, upper]) for that family, with a fractional bin edge."""
    cell = policy["cells"]["%s|%d_%d" % (material, family[0], family[1])]
    edges = np.asarray(policy["edges"], dtype=np.float64)
    p = np.asarray(cell["p"], dtype=np.float64)
    lo = np.log(max(float(lower), 1.0))
    hi = np.log(float(upper)) if upper is not None and np.isfinite(upper) else edges[-1] + 1.0
    if hi <= edges[0] or lo >= edges[-1]:
        return 0.0
    mass = 0.0
    for i in range(len(p)):
        a, b = edges[i], edges[i + 1]
        overlap = max(0.0, min(b, hi) - max(a, lo))
        if overlap > 0.0:
            mass += p[i] * overlap / (b - a)
    return float(mass)


def weights(policy, material, lower, upper=None, allowed=None, floor_frac=0.05,
            prior=None):
    """Normalised family weights.  floor_frac keeps a floor of exploration."""
    families = [tuple(f) for f in allowed] if allowed else list(FAMILIES)
    for family in families:
        if family not in FAMILIES:
            raise ValueError("unknown family %s" % (family,))
    base = np.array([band_mass(policy, material, f, lower, upper) for f in families])
    if prior is not None:
        base = base * np.asarray(prior, dtype=np.float64)
    if base.max() <= 0.0:
        base = np.ones(len(families))
    base = np.maximum(base, floor_frac * base.max())
    w = base / base.sum()
    return {"families": families, "w": w.tolist(),
            "effective": float(np.exp(-(w * np.log(w)).sum())),
            "raw_mass": [float(v) for v in
                         (base / base.sum()).tolist()]}


def sample(weights_row, n, rng):
    families = weights_row["families"]
    w = np.asarray(weights_row["w"], dtype=np.float64)
    pick = rng.choice(len(families), size=n, p=w)
    return [families[i] for i in pick]


def expected_rate(policy, material, lower, upper, weights_row):
    """The family-marginal in-band rate the policy implies, from the same pool."""
    w = np.asarray(weights_row["w"], dtype=np.float64)
    rate = np.array([band_mass(policy, material, f, lower, upper)
                     for f in weights_row["families"]])
    return float((w * rate).sum())


def cross_validate(ctx, specs, folds=5, seed=0):
    """Leakage-free check: fit the histogram on 4/5 of the pool, score on 1/5.

    Compares the family-marginal in-band rate of the policy against uniform
    family sampling on data the histogram never saw.
    """
    cs1 = np.log(np.maximum(ctx["Y"][:, 0], 1.0))
    edges = _grid(ctx)
    mat, nd, nb = ctx["material"], ctx["nd"], ctx["nb"]
    rng = np.random.default_rng(seed)
    rows = {}
    for spec in specs:
        pol_rates, uni_rates, pol_all, uni_all = [], [], [], []
        for fold in range(folds):
            pol = {"edges": edges.tolist(), "cells": {}}
            held = {}
            for material in S.MATERIAL_ORDER:
                for family in FAMILIES:
                    sel = np.where((mat == material) & (nd == family[0]) & (nb == family[1]))[0]
                    rng.shuffle(sel)
                    cut = len(sel) // folds
                    test = sel[fold * cut:(fold + 1) * cut]
                    train = np.setdiff1d(sel, test, assume_unique=False)
                    counts, _ = np.histogram(cs1[train], bins=edges)
                    counts = _smooth(counts.astype(np.float64) + ALPHA)
                    pol["cells"]["%s|%d_%d" % (material, family[0], family[1])] = {
                        "p": (counts / counts.sum()).tolist()}
                    held["%s|%d_%d" % (material, family[0], family[1])] = test
            wrow = weights(pol, spec["material"], spec["lower"], spec.get("upper"))
            lo, hi = float(spec["lower"]), float(spec.get("upper") or np.inf)
            rates, counts = [], []
            for family in FAMILIES:
                sel = held["%s|%d_%d" % (spec["material"], family[0], family[1])]
                v = np.exp(cs1[sel])
                rates.append(float(((v >= lo) & (v <= hi)).mean()) if len(v) else 0.0)
                counts.append(len(v))
            rates = np.array(rates)
            w = np.asarray(wrow["w"], dtype=np.float64)
            pol_rates.append(float((w * rates).sum()))
            uni_rates.append(float(rates.mean()))
            pol_all.append(float((w * rates * counts).sum()))
            uni_all.append(float((rates * counts).mean()))
        rows[spec["name"]] = {
            "policy_rate_mean": float(np.mean(pol_rates)),
            "uniform_rate_mean": float(np.mean(uni_rates)),
            "gain": float(np.mean(pol_rates) / max(np.mean(uni_rates), 1e-9)),
            "policy_rate_weighted": float(np.mean(pol_all)),
            "uniform_rate_weighted": float(np.mean(uni_all)),
            "effective_families": float(weights(
                fit(ctx), spec["material"], spec["lower"], spec.get("upper"))["effective"]),
        }
    return rows